site_name: FAQ Infrastrukturförderprogramm
site_url: https://ifpstz.github.io/ifp-faq/
theme:
  name: material
  custom_dir: overrides
  language: de

  # Navigation
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy

  # Heller & dunkler Modus
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: hellen Modus aktivieren

  # Schriftarten auf Berlin Type umstellen
  font:
    text: "Berlin Type"
    code: "Fira Code"

nav:
  - Home: index.md
  - ... # Hier fügt Awesome Pages alle restlichen Ordner/Dateien automatisch ein

extra_css:
  - styles/berlin.css
extra_templates:
  - admin/index.html
  - admin/config.yml

plugins:
  - search
  - blog
  - awesome-pages
  - mkdocs-nav-weight
markdown_extensions:
  - attr_list
